/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.metacustomer;

import io.socket.client.Socket;
import java.awt.BorderLayout;
import javax.swing.JSplitPane;

/**
 *
 * @author kapilrohilla
 */
public class MergePanel extends javax.swing.JPanel {

    /**
     * Creates new form MergePanel
     */
    public MergePanel() {
        framesetup();
    }
    
      public void framesetup(){
        NavigationTree bottomPanel_navigator = new NavigationTree();
//        TopPanelMarketData topPanel_marketData = new TopPanelMarketData();
        JSplitPane jSplitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, new LeftPanel(), bottomPanel_navigator);
        jSplitPane.setDividerLocation(300);
        setLayout(new BorderLayout());
        add(jSplitPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
