/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.metacustomer;

import io.socket.client.Socket;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JSplitPane;

import com.mycompany.metacustomer.Utility.APIs;
import javax.swing.JPanel;

/**
 *
 * @author kapilrohilla
 */
public final class OrderFrame extends javax.swing.JDialog {

    public static MainFrame leftPanel;
    /**
     * Creates new form OrderFrame
     *
     * @param engine
     */

    public static String chartUrl = APIs.CHART + "?symbol=XAUUSD";

    public OrderFrame() {
        setTitle("New Order");
        setModal(true);
        
        this.setSize(800, 600);
        try {
            leftPanel = new MainFrame(chartUrl, false, false);
        } catch (Exception e) {
            e.printStackTrace();
        }

        splittedFrame();
//        this.setVisible(true);
    }

    public OrderFrame(String symbol) {
//        setTitle("New Order");
        
//        try {
//            leftPanel = new MainFrame(chartUrl, false, false);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

        setModal(true);
        
        this.setSize(800, 600);
        splittedFrame(symbol);
        
        // this.setVisible(true);
    }

    void splittedFrame(String symbol) {

        OrderRightPanel rightPanel = new OrderRightPanel(symbol);

//        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, new JPanel(), rightPanel);
//        if (leftPanel != null) {
//            Dimension minimumSize = new Dimension(350, 600);
//            leftPanel.setMinimumSize(minimumSize);
//            rightPanel.setMinimumSize(minimumSize);
//        }
        add(rightPanel);
    }

    void splittedFrame() {

        OrderRightPanel rightPanel = new OrderRightPanel();

//        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, new JPanel(), rightPanel);
//        if (leftPanel != null) {
//            Dimension minimumSize = new Dimension(350, 600);
//            leftPanel.setMinimumSize(minimumSize);
//            rightPanel.setMinimumSize(minimumSize);
//        }
        add(rightPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Engine engine = Engine.newInstance(
//            EngineOptions.newBuilder(RenderingMode.OFF_SCREEN)
//                    .licenseKey("6P830J66YCGSBFUHVSJ6EF1W6C8XJKFFR6HW912I9DWC7DI1AXB5ZZFGPHOJGXN3G6JQ")
//                    .build());
//                 new OrderFrame().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
